@startuml 演習3-2_CL_医師と患者と医局と診療記録
class 医師 {
  - 名前
  - 所属医局
  + 診察(患者)
  + 診察記録作成(患者)
}

class 患者 {
  - 名前
  - 担当医
  + 診察受診(医師)
}

class 診察記録 {
  - 内容
}

class 医局 {
  - 名前
}

医師 "1" -up- "n" 患者 : 担当
医師 "1" -- "1" 医局 : 所属
医師 "0..*" -- "1" 診察記録 : 作成
患者 "1" -- "0..1" 医師 : 受診
@enduml