@startuml 演習6-5-3_ステートマシン図_ライントレーサー
scale 600 width

[*] --> 電源SW_OFF

state 電源SW_OFF {
  [*] --> 電源SW_ON : 電源SWをONにする
}

state 電源SW_ON {
  state 右旋回 {
    [*] --> 暗い : 光センサーが黒いライン上にある
    暗い --> 右旋回 : ライントレーサーは右旋回を始める
    右旋回 --> 明るい : 光センサーがラインを外れる
  }

  state 左旋回 {
    明るい --> 左旋回 : ライントレーサーは左旋回を始める
    左旋回 --> 暗い : 光センサーが黒いライン上にある
  }

  明るい --> 右旋回 : 光センサーが黒いライン上にある
  右旋回 --> [*] : 電源SWを切る
}

@enduml